name = "ModelWeights"
uuid = "933925d5-f025-4d5f-a75f-f973a6ce34d8"
version = "0.1.0"
authors = ["Britta Grusdt <britta.grusdt@awi.de>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearRegression = "92481ed7-9fb7-40fd-80f2-46fd0f076581"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[compat]
CSV = "0.10.15"
Colors = "0.12.11"
DataFrames = "1.7.0"
DiskArrays = "0.4.14"
Distributions = "0.25.117"
FillArrays = "1.15.0"
JLD2 = "0.5.10"
JuliaFormatter = "2.1.2"
LinearRegression = "0.2.1"
Logging = "1.11.0"
MCMCChains = "7.4.0"
Missings = "1.2.0"
Serialization = "1.11.0"
Setfield = "1.1.1"
StatsBase = "0.34.6"
StatsPlots = "0.15.8"
Turing = "0.40.3"
YAXArrays = "0.6.1"
